use std::env;

pub struct Config {
  pub port: u64,
  pub postgres_uri: String,
  pub redis_host: String,
  pub redis_password: String,
  pub redis_port: u16,
  pub firebase_auth_key: String,
  pub cors_origin: Vec<String>,
  pub canva_key: String,
  pub stripe_key: String,
  pub stripe_webhook_key: String,
  pub minio_region: String,
  pub minio_bucket: String,
  pub minio_access_key: String,
  pub minio_secret_key: String,
  pub aws_rekognition_access_key: String,
  pub aws_rekognition_secret_key: String,
  pub aws_rekognition_region: String,
  // Rabbitmq envs
  pub rabbitmq_uri: String,
  pub exchange_name: String,
  pub retry_ttl: u32,
  pub sui_rpc: String,
  pub ticketland_api: String,
  pub ticketland_dapp: String,
  pub ticket_purchase_protocol_fee: i64,
  pub secondary_market_protocol_fee: i64,
  pub ticket_verifier_priv_key: String,
  pub max_image_size: usize,
  pub image_recognition_confidence: f32,
  pub arweave_jwk_key: String,
  pub arweave_gateway: String,
  pub arweave_reward_multiplier: f32,
}

impl Config {
  pub fn new() -> Result<Self, env::VarError> {
    Result::Ok(
      Self {
        port: env::var("PORT").unwrap().parse::<u64>().unwrap(),
        postgres_uri: env::var("POSTGRES_URI").unwrap(),
        redis_host: env::var("REDIS_HOST").unwrap(),
        redis_password: env::var("REDIS_PASSWORD").unwrap(),
        redis_port: env::var("REDIS_PORT").unwrap().parse::<u16>().unwrap(),
        firebase_auth_key: env::var("FIREBASE_API_KEY").unwrap(),
        cors_origin: env::var("CORS_ORIGIN").unwrap().split(",").map(|val| val.to_owned()).collect(),
        minio_region: env::var("MINIO_REGION").unwrap(),
        minio_bucket: env::var("NFT_BUCKET").unwrap(),
        minio_access_key: env::var("MINIO_ACCESS_KEY").unwrap(),
        minio_secret_key: env::var("MINIO_SECRET_KEY").unwrap(),
        aws_rekognition_access_key: env::var("AWS_REKOGNITION_ACCESS_KEY").unwrap(),
        aws_rekognition_secret_key: env::var("AWS_REKOGNITION_SECRET_KEY").unwrap(),
        aws_rekognition_region: env::var("AWS_REKOGNITION_REGION").unwrap(),
        rabbitmq_uri: env::var("RABBITMQ_URI").unwrap(),
        exchange_name: env::var("EXCHANGE_NAME").unwrap(),
        retry_ttl: env::var("RETRY_TTL").unwrap().parse::<u32>().unwrap(),
        sui_rpc: env::var("SUI_RPC").unwrap(),
        canva_key: env::var("CANVA_CLIENT_SECRET").unwrap(),
        stripe_key: env::var("STRIPE_CLIENT_SECRET").unwrap(),
        stripe_webhook_key: env::var("STRIPE_WEBHOOK_SECRET").unwrap(),
        ticketland_api: env::var("TICKETLAND_API").unwrap(),
        ticketland_dapp: env::var("TICKETLAND_DAPP").unwrap(),
        ticket_purchase_protocol_fee: env::var("TICKET_PURCHASE_PROTOCOL_FEE").unwrap().parse::<i64>().unwrap(),
        secondary_market_protocol_fee: env::var("SECONDARY_MARKET_PROTOCOL_FEE").unwrap().parse::<i64>().unwrap(),
        ticket_verifier_priv_key: env::var("TICKET_VERIFIER_PRIV_KEY").unwrap(),
        max_image_size: env::var("MAX_IMAGE_SIZE").unwrap().parse::<usize>().unwrap(),
        image_recognition_confidence: env::var("IMAGE_RECOGNITION_CONFIDENCE").unwrap().parse::<f32>().unwrap(),
        arweave_jwk_key: env::var("ARWEAVE_JWK_KEY").unwrap(),
        arweave_gateway: env::var("ARWEAVE_GATEWAY").unwrap(),
        arweave_reward_multiplier: env::var("ARWEAVE_REWARD_MULTIPLIER").unwrap().parse::<f32>().unwrap(),
      }
    )
  }
}
