[package]
name = "ticketland-api"
version = "0.1.0"
edition = "2021"
license = "BUSL-1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.2"
actix-web = "4.0.1"
actix-cors = "0.6.1"
actix-multipart = "0.4.0"
bytes = "1.2.0"
borsh = "0.9.3"
env_logger = "0.9.0"
eyre = "0.6.8"
dotenv = "0.15"
futures-util = "0.3.15"
futures = "0.3.12"
ticketland-core = { git = "https://github.com/ticketland-io/common-rust", version = "0.2.4" }
api-helpers = { git = "https://github.com/ticketland-io/common-rust", version = "0.2.5" }
common-data = { git = "https://github.com/ticketland-io/common-rust", version = "0.2.19" }
amqp-helpers = { git = "https://github.com/ticketland-io/amqp-helpers", version = "0.1.6" }
ticketland-event-handler = { git = "https://github.com/ticketland-io/ticketland-event-handler", version = "0.1.2" }
program-artifacts = { git = "https://github.com/ticketland-io/program-artifacts", version = "0.1.10" }
solana-web3-rust = { git = "https://github.com/ticketland-io/solana-web3-rust", version = "0.1.4" }
chrono = "0.4.21"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.14.1" }
tokio-util = { version = "0.7.1" }
mime = "0.3.16"
solana-sdk = "1.11.10"
solana-client = "1.11.10"
keccak-hash = "0.9.0"
bs58 = "0.4.0"
thiserror = "1.0.33"
async-stripe = { version = "0.15.0", features = ["runtime-tokio-hyper", "checkout", "connect"] }
