[package]
name = "ticketland-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.2"
actix-web = "4.0.1"
actix-cors = "0.6.1"
actix-multipart = "0.4.0"
env_logger = "0.9.0"
dotenv = "0.15"
futures-util = "0.3.15"
ticketland-core = { git = "https://github.com/ticketland-io/common-rust" }
api-helpers = { git = "https://github.com/ticketland-io/common-rust" }
common-data = { git = "https://github.com/ticketland-io/common-rust" }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.14.1" }
tokio-util = { version = "0.7.1" }
